name: Build a Openwrt image

on:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'
jobs:
  build:
    runs-on: ubuntu-22.04
